Using stderr for error message
Redirecting error message to standard error

diff --git a/dass b/dass
--- a/dass
+++ b/dass
@@ -35,7 +35,7 @@ then
 
 else
 
-    echo "Error: No config file."
+    (>&2 echo "Error: No config file.")
 
 fi
 
